gantt
	title Honours Project Schedule
	dateFormat DD-MM-YYYY
	excludes weekends
	axisFormat  %d/%m
	todayMarker off
	
	section Lit Review
	Initial Research :l1, 21-09-2020, 10d
	First Draft :l2, after l1  , 15d
	Final Draft :l3, after l2, 15d 
         
	section Development
	Data Collection :after l1, 15d
	Prototype: 10d
	Test: 10d
	Refine Program: 15d
	Analysis: d5, 15d		

	section Admin
	Project Planning: 21-09-2020, 5d
	IPO :21-09-2020, 10d
	Prep Interim Report :01-11-2020, 5d
	Poster :01-04-2021, 5d
	Finalise Dissertation: 01-03-2021, 30d
	
	section Deadlines
	IPO Submission :crit, 25-09-2020, 1d
	Interim Report :crit, 06-11-2020, 1d
	Submission :crit, 21-04-2021, 1d

